=== CesarMaalouf/ggobi/data/ggobi.dtd
<!--
  The DTD for the GGobi input file format.
  See data/flea.xml in the distribution for an example.
 -->

<!ENTITY % glyphTypes " plus | x | oc | or | fc | fr | . ">
<!ENTITY % Boolean    " true | T | TRUE | false | F | FALSE ">

<!ELEMENT description ( #PCDATA )>
<!ATTLIST description
  source CDATA #IMPLIED
>  

<!ELEMENT variables ( variable|realvariable|categoricalvariable|integervariable|countervariable )*>

<!-- Allows the name to be the only entry -->
<!ELEMENT variable ( #PCDATA )>
<!ELEMENT realvariable ( (description)?,(quickHelp)? )>

<!ELEMENT categoricalvariable (description?, quickHelp?, levels, time?)?>
<!ELEMENT countervariable EMPTY>
<!ELEMENT integervariable (description?, quickHelp?, time?)>


<!ELEMENT level (#PCDATA)>
<!ATTLIST level
  value CDATA #IMPLIED
>

<!ELEMENT levels (level)+>
<!ATTLIST levels 
   count CDATA #REQUIRED
>

<!ELEMENT quickHelp (#PCDATA)>
<!ELEMENT time (#PCDATA)>


<!ELEMENT records ( record )*>
<!ELEMENT record  (#PCDATA|int|real|na|string)*>

<!ELEMENT ggobidata ((brush)?, (activeColorScheme)?, (data|edges)+)>


<!-- I don't see how a datad can have a colormap -->
<!ELEMENT data ((description)?, (colormap)?, variables, records, (edges)?)>

<!ELEMENT color ( #PCDATA) >
<!-- id is a number or either of "fg" and "bg" -->
<!ATTLIST color  
    id       CDATA  #IMPLIED
    r        CDATA  #IMPLIED
    g        CDATA  #IMPLIED
    b        CDATA  #IMPLIED
    range    CDATA  #IMPLIED
    name     CDATA  #IMPLIED
>

<!ELEMENT edge EMPTY>


<!ELEMENT edges (data*, edge+)>
<!ATTLIST edges 
     name  CDATA #IMPLIED
     count CDATA #REQUIRED
     data  CDATA #IMPLIED
>

<!ELEMENT activeColorScheme ( #PCDATA ) >
<!ATTLIST activeColorScheme
    name     CDATA   #IMPLIED
    file     CDATA   #IMPLIED
>
      
<!ELEMENT colormap (color)+ >
<!ATTLIST colormap
      size  CDATA  #REQUIRED
      range CDATA  #IMPLIED
      file  CDATA   #IMPLIED
      type  CDATA   "(xml | table)"
>
         

<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>



<!ATTLIST records
   count CDATA  #REQUIRED
   missingValue CDATA #IMPLIED
   color        CDATA #IMPLIED
   glyph        CDATA #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED   
>


<!ATTLIST variables
  count CDATA #REQUIRED
>

<!ENTITY % VariableAttributes "name          NMTOKEN #IMPLIED
    nickname      NMTOKEN #IMPLIED
    transformName NMTOKEN #IMPLIED
    missingValue  CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED">

<!ATTLIST variable
  %VariableAttributes;
>

<!ATTLIST integervariable
  %VariableAttributes;
>

<!ATTLIST countervariable
  %VariableAttributes;
>


<!ATTLIST realvariable
    name          CDATA   #IMPLIED
    nickname      NMTOKEN #IMPLIED
    quickHelp     CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    transformName CDATA   #IMPLIED
    missingValue  CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED
>

<!ATTLIST categoricalvariable
    name          NMTOKEN #IMPLIED
    nickname      NMTOKEN #IMPLIED
    quickHelp     CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    transformName NMTOKEN #IMPLIED
    missingValue  CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED
    levels        CDATA   "auto"
    count         CDATA   #IMPLIED
>

<!ATTLIST record
   label     CDATA                     #IMPLIED
   id        CDATA                     #IMPLIED
   color     CDATA                     #IMPLIED
   glyph     CDATA                     #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED
   hidden    ( %Boolean; )             "FALSE"

   source      CDATA  #IMPLIED
   destination CDATA  #IMPLIED
>   

<!ATTLIST edge
   source      CDATA  #REQUIRED
   destination CDATA  #REQUIRED
   color       CDATA  #IMPLIED
   width       CDATA  #IMPLIED
>


<!ATTLIST data
   name         CDATA #IMPLIED
   nickname     NMTOKEN #IMPLIED
   count        CDATA #IMPLIED
   missingValue CDATA #IMPLIED
   color        CDATA #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED   
>

<!-- to initialize the brushing color and glyph -->
<!ELEMENT brush ( #PCDATA )>
<!ATTLIST brush
   color        CDATA #IMPLIED
   glyph        CDATA #IMPLIED
>

<!ATTLIST ggobidata
    count  CDATA #IMPLIED
    ids    (alpha)  #IMPLIED
>

<!ELEMENT real ( #PCDATA )>
<!ELEMENT int ( #PCDATA )>
<!ELEMENT string ( #PCDATA )>
<!ELEMENT na EMPTY>

=== CesarMaalouf/ggobi/data/river.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata count="1">
<data numRecords="128">
<description>
Andreas says: The river data I got from Don Percival, Applied Physics
Lab, Seattle, but I wouldn't know whether he is the proper source.
What you need to know: the data are monthly average river flow level
of Willamette River in Oregon.  I don't know anymore the particular
years.
</description>
<variables count="3">
<variable>Time</variable>
<variable>Flow</variable>
<variable>Lag1</variable>
</variables>
<records
 count="128" glyph="fr 1" color="5">
<record label="1">
1.000 8.954 8.954
</record>
<record label="2">
2.000 9.494 8.954
</record>
<record label="3">
3.000 10.194 9.494
</record>
<record label="4">
4.000 10.957 10.194
</record>
<record label="5">
5.000 11.078 10.957
</record>
<record label="6">
6.000 10.982 11.078
</record>
<record label="7">
7.000 10.490 10.982
</record>
<record label="8">
8.000 10.275 10.490
</record>
<record label="9">
9.000 10.166 10.275
</record>
<record label="10">
10.000 9.235 10.166
</record>
<record label="11">
11.000 8.565 9.235
</record>
<record label="12">
12.000 8.511 8.565
</record>
<record label="13">
13.000 10.121 8.511
</record>
<record label="14">
14.000 11.185 10.121
</record>
<record label="15">
15.000 10.935 11.185
</record>
<record label="16">
16.000 11.180 10.935
</record>
<record label="17">
17.000 10.957 11.180
</record>
<record label="18">
18.000 10.568 10.957
</record>
<record label="19">
19.000 10.140 10.568
</record>
<record label="20">
20.000 9.995 10.140
</record>
<record label="21">
21.000 9.142 9.995
</record>
<record label="22">
22.000 8.612 9.142
</record>
<record label="23">
23.000 8.389 8.612
</record>
<record label="24">
24.000 8.388 8.389
</record>
<record label="25">
25.000 9.975 8.388
</record>
<record label="26">
26.000 10.268 9.975
</record>
<record label="27">
27.000 11.051 10.268
</record>
<record label="28">
28.000 10.517 11.051
</record>
<record label="29">
29.000 10.969 10.517
</record>
<record label="30">
30.000 10.431 10.969
</record>
<record label="31">
31.000 10.410 10.431
</record>
<record label="32">
32.000 10.080 10.410
</record>
<record label="33">
33.000 9.589 10.080
</record>
<record label="34">
34.000 9.409 9.589
</record>
<record label="35">
35.000 8.587 9.409
</record>
<record label="36">
36.000 8.532 8.587
</record>
<record label="37">
37.000 8.401 8.532
</record>
<record label="38">
38.000 8.295 8.401
</record>
<record label="39">
39.000 9.696 8.295
</record>
<record label="40">
40.000 11.410 9.696
</record>
<record label="41">
41.000 11.216 11.410
</record>
<record label="42">
42.000 10.417 11.216
</record>
<record label="43">
43.000 10.047 10.417
</record>
<record label="44">
44.000 10.374 10.047
</record>
<record label="45">
45.000 10.134 10.374
</record>
<record label="46">
46.000 9.142 10.134
</record>
<record label="47">
47.000 8.697 9.142
</record>
<record label="48">
48.000 9.047 8.697
</record>
<record label="49">
49.000 9.874 9.047
</record>
<record label="50">
50.000 11.420 9.874
</record>
<record label="51">
51.000 10.782 11.420
</record>
<record label="52">
52.000 11.207 10.782
</record>
<record label="53">
53.000 10.273 11.207
</record>
<record label="54">
54.000 10.290 10.273
</record>
<record label="55">
55.000 9.499 10.290
</record>
<record label="56">
56.000 9.645 9.499
</record>
<record label="57">
57.000 9.204 9.645
</record>
<record label="58">
58.000 8.791 9.204
</record>
<record label="59">
59.000 9.013 8.791
</record>
<record label="60">
60.000 9.221 9.013
</record>
<record label="61">
61.000 9.586 9.221
</record>
<record label="62">
62.000 9.804 9.586
</record>
<record label="63">
63.000 10.516 9.804
</record>
<record label="64">
64.000 10.024 10.516
</record>
<record label="65">
65.000 9.966 10.024
</record>
<record label="66">
66.000 10.754 9.966
</record>
<record label="67">
67.000 10.245 10.754
</record>
<record label="68">
68.000 10.096 10.245
</record>
<record label="69">
69.000 9.381 10.096
</record>
<record label="70">
70.000 8.837 9.381
</record>
<record label="71">
71.000 8.880 8.837
</record>
<record label="72">
72.000 9.706 8.880
</record>
<record label="73">
73.000 10.474 9.706
</record>
<record label="74">
74.000 11.503 10.474
</record>
<record label="75">
75.000 11.589 11.503
</record>
<record label="76">
76.000 10.626 11.589
</record>
<record label="77">
77.000 10.658 10.626
</record>
<record label="78">
78.000 10.540 10.658
</record>
<record label="79">
79.000 10.286 10.540
</record>
<record label="80">
80.000 10.007 10.286
</record>
<record label="81">
81.000 9.297 10.007
</record>
<record label="82">
82.000 8.781 9.297
</record>
<record label="83">
83.000 8.835 8.781
</record>
<record label="84">
84.000 8.912 8.835
</record>
<record label="85">
85.000 10.184 8.912
</record>
<record label="86">
86.000 10.641 10.184
</record>
<record label="87">
87.000 10.033 10.641
</record>
<record label="88">
88.000 9.880 10.033
</record>
<record label="89">
89.000 11.278 9.880
</record>
<record label="90">
90.000 10.429 11.278
</record>
<record label="91">
91.000 9.787 10.429
</record>
<record label="92">
92.000 9.458 9.787
</record>
<record label="93">
93.000 8.811 9.458
</record>
<record label="94">
94.000 8.651 8.811
</record>
<record label="95">
95.000 8.802 8.651
</record>
<record label="96">
96.000 9.164 8.802
</record>
<record label="97">
97.000 9.395 9.164
</record>
<record label="98">
98.000 10.460 9.395
</record>
<record label="99">
99.000 11.100 10.460
</record>
<record label="100">
100.000 11.167 11.100
</record>
<record label="101">
101.000 10.491 11.167
</record>
<record label="102">
102.000 10.091 10.491
</record>
<record label="103">
103.000 10.024 10.091
</record>
<record label="104">
104.000 9.525 10.024
</record>
<record label="105">
105.000 9.023 9.525
</record>
<record label="106">
106.000 8.733 9.023
</record>
<record label="107">
107.000 8.824 8.733
</record>
<record label="108">
108.000 9.072 8.824
</record>
<record label="109">
109.000 10.437 9.072
</record>
<record label="110">
110.000 10.387 10.437
</record>
<record label="111">
111.000 10.852 10.387
</record>
<record label="112">
112.000 10.913 10.852
</record>
<record label="113">
113.000 9.936 10.913
</record>
<record label="114">
114.000 10.263 9.936
</record>
<record label="115">
115.000 10.024 10.263
</record>
<record label="116">
116.000 9.451 10.024
</record>
<record label="117">
117.000 8.810 9.451
</record>
<record label="118">
118.000 8.616 8.810
</record>
<record label="119">
119.000 8.892 8.616
</record>
<record label="120">
120.000 9.706 8.892
</record>
<record label="121">
121.000 9.598 9.706
</record>
<record label="122">
122.000 9.705 9.598
</record>
<record label="123">
123.000 9.638 9.705
</record>
<record label="124">
124.000 10.682 9.638
</record>
<record label="125">
125.000 10.659 10.682
</record>
<record label="126">
126.000 10.701 10.659
</record>
<record label="127">
127.000 10.417 10.701
</record>
<record label="128">
128.000 10.200 10.417
</record>
</records>
</data>
</ggobidata>

=== CesarMaalouf/ggobi/data/buckyball.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata count="2">
<data name="buckyball nodes">
<description>
</description>
<variables count="3">
  <realvariable name="v1" />
  <realvariable name="v2" />
  <realvariable name="v3" />
</variables>
<records count="60" color="2" glyph="plus 0">
<record id="1"> -0.108022 2.389616 -2.593673 </record>
<record id="2"> -1.232478 2.765126 -1.802246 </record>
<record id="3"> -0.751701 3.377841 -0.613467 </record>
<record id="4"> 0.671924 3.384590 -0.665701 </record>
<record id="5"> 1.066695 2.778224 -1.884692 </record>
<record id="6"> -2.975723 0.176517 1.933305 </record>
<record id="7"> -3.453261 -0.435074 0.758800 </record>
<record id="8"> -3.011595 -1.788106 0.739593 </record>
<record id="9"> -2.251138 -2.005841 1.932052 </record>
<record id="10"> -2.225179 -0.792532 2.668610 </record>
<record id="11"> 3.131426 0.187348 1.668036 </record>
<record id="12"> 2.436158 -0.788283 2.480008 </record>
<record id="13"> 2.405963 -2.015362 1.724938 </record>
<record id="14"> 3.061083 -1.789611 0.493145 </record>
<record id="15"> 3.503849 -0.429040 0.482560 </record>
<record id="16"> -0.131939 1.150449 -3.349970 </record>
<record id="17"> -1.289658 0.308857 -3.298775 </record>
<record id="18"> -0.848418 -1.052649 -3.307085 </record>
<record id="19"> 0.583910 -1.046871 -3.365774 </record>
<record id="20"> 1.033339 0.317287 -3.386985 </record>
<record id="21"> 0.731139 -3.472222 0.614752 </record>
<record id="22"> -0.687668 -3.471748 0.665525 </record>
<record id="23"> -1.075166 -2.858685 1.890461 </record>
<record id="24"> 0.104362 -2.475031 2.592667 </record>
<record id="25"> 1.217345 -2.857368 1.804314 </record>
<record id="26"> -2.439934 0.694554 -2.483608 </record>
<record id="27"> -3.115184 -0.285093 -1.704905 </record>
<record id="28"> -3.505883 0.324700 -0.481919 </record>
<record id="29"> -3.068511 1.682535 -0.508266 </record>
<record id="30"> -2.407917 1.907850 -1.747466 </record>
<record id="31"> 0.791212 2.923079 1.789715 </record>
<record id="32"> 1.444547 3.159690 0.539726 </record>
<record id="33"> 2.671233 1.591056 1.681337 </record>
<record id="34"> 2.605742 2.324577 0.497151 </record>
<record id="35"> 1.558792 1.983222 2.466817 </record>
<record id="36"> 0.651220 -3.018531 -1.845944 </record>
<record id="37"> 1.337684 -2.047819 -2.621833 </record>
<record id="38"> 1.404882 -3.248422 -0.655727 </record>
<record id="39"> 2.558580 -2.412477 -0.718711 </record>
<record id="40"> 2.520522 -1.674419 -1.913518 </record>
<record id="41"> -2.663924 -1.670388 -1.712625 </record>
<record id="42"> -1.540988 -2.044622 -2.510036 </record>
<record id="43"> -0.798963 -3.019611 -1.785560 </record>
<record id="44"> -1.459231 -3.244257 -0.550463 </record>
<record id="45"> -2.610975 -2.409814 -0.507085 </record>
<record id="46"> -0.600661 0.991026 3.343135 </record>
<record id="47"> -1.009735 -0.397655 3.388172 </record>
<record id="48"> 0.142193 -1.227663 3.347725 </record>
<record id="49"> 0.850951 0.955020 3.301366 </record>
<record id="50"> 1.349409 -0.412905 3.264122 </record>
<record id="51"> -1.423823 3.147125 0.657111 </record>
<record id="52"> -2.573165 2.306380 0.706583 </record>
<record id="53"> -2.523919 1.564246 1.918381 </record>
<record id="54"> -1.339441 1.943759 2.623628 </record>
<record id="55"> -0.665066 2.924495 1.838100 </record>
<record id="56"> 3.012250 1.698325 -0.738779 </record>
<record id="57"> 3.458585 0.330149 -0.748281 </record>
<record id="58"> 2.976355 -0.280454 -1.937521 </record>
<record id="59"> 2.248435 0.708226 -2.654087 </record>
<record id="60"> 2.259493 1.927785 -1.914609 </record>
</records>
</data>

<data name="edges">
<records count="90" glyph="fr 0">
<record source="59" destination="60" color="2"> </record>
<record source="58" destination="59" color="2"> </record>
<record source="57" destination="58" color="2"> </record>
<record source="56" destination="57" color="2"> </record>
<record source="56" destination="60" color="2"> </record>
<record source="54" destination="55" color="2"> </record>
<record source="53" destination="54" color="2"> </record>
<record source="52" destination="53" color="2"> </record>
<record source="51" destination="52" color="2"> </record>
<record source="51" destination="55" color="2"> </record>
<record source="49" destination="50" color="2"> </record>
<record source="48" destination="50" color="2"> </record>
<record source="47" destination="48" color="2"> </record>
<record source="46" destination="54" color="4"> </record>
<record source="46" destination="49" color="2"> </record>
<record source="46" destination="47" color="2"> </record>
<record source="44" destination="45" color="2"> </record>
<record source="43" destination="44" color="2"> </record>
<record source="42" destination="43" color="2"> </record>
<record source="41" destination="42" color="2"> </record>
<record source="41" destination="45" color="2"> </record>
<record source="40" destination="58" color="4"> </record>
<record source="39" destination="40" color="2"> </record>
<record source="38" destination="39" color="2"> </record>
<record source="37" destination="40" color="2"> </record>
<record source="36" destination="43" color="4"> </record>
<record source="36" destination="38" color="2"> </record>
<record source="36" destination="37" color="2"> </record>
<record source="35" destination="49" color="4"> </record>
<record source="34" destination="56" color="4"> </record>
<record source="33" destination="34" color="2"> </record>
<record source="33" destination="35" color="2"> </record>
<record source="32" destination="34" color="2"> </record>
<record source="31" destination="55" color="4"> </record>
<record source="31" destination="35" color="2"> </record>
<record source="31" destination="32" color="2"> </record>
<record source="29" destination="52" color="4"> </record>
<record source="29" destination="30" color="2"> </record>
<record source="28" destination="29" color="2"> </record>
<record source="27" destination="41" color="4"> </record>
<record source="27" destination="28" color="2"> </record>
<record source="26" destination="30" color="2"> </record>
<record source="26" destination="27" color="2"> </record>
<record source="24" destination="48" color="4"> </record>
<record source="24" destination="25" color="2"> </record>
<record source="23" destination="24" color="2"> </record>
<record source="22" destination="44" color="4"> </record>
<record source="22" destination="23" color="2"> </record>
<record source="21" destination="38" color="4"> </record>
<record source="21" destination="25" color="2"> </record>
<record source="21" destination="22" color="2"> </record>
<record source="20" destination="59" color="4"> </record>
<record source="19" destination="37" color="4"> </record>
<record source="19" destination="20" color="2"> </record>
<record source="18" destination="42" color="4"> </record>
<record source="18" destination="19" color="2"> </record>
<record source="17" destination="26" color="4"> </record>
<record source="17" destination="18" color="2"> </record>
<record source="16" destination="20" color="2"> </record>
<record source="16" destination="17" color="2"> </record>
<record source="15" destination="57" color="4"> </record>
<record source="14" destination="39" color="4"> </record>
<record source="14" destination="15" color="2"> </record>
<record source="13" destination="25" color="4"> </record>
<record source="13" destination="14" color="2"> </record>
<record source="12" destination="50" color="4"> </record>
<record source="12" destination="13" color="2"> </record>
<record source="11" destination="33" color="4"> </record>
<record source="11" destination="12" color="2"> </record>
<record source="11" destination="15" color="2"> </record>
<record source="10" destination="47" color="4"> </record>
<record source="9" destination="23" color="4"> </record>
<record source="9" destination="10" color="2"> </record>
<record source="8" destination="45" color="4"> </record>
<record source="8" destination="9" color="2"> </record>
<record source="7" destination="28" color="4"> </record>
<record source="7" destination="8" color="2"> </record>
<record source="6" destination="53" color="4"> </record>
<record source="6" destination="7" color="2"> </record>
<record source="6" destination="10" color="2"> </record>
<record source="5" destination="60" color="4"> </record>
<record source="4" destination="32" color="4"> </record>
<record source="4" destination="5" color="2"> </record>
<record source="3" destination="51" color="4"> </record>
<record source="3" destination="4" color="2"> </record>
<record source="2" destination="30" color="4"> </record>
<record source="2" destination="3" color="2"> </record>
<record source="1" destination="16" color="4"> </record>
<record source="1" destination="5" color="2"> </record>
<record source="1" destination="2" color="2"> </record>
</records>
</data>

</ggobidata>

=== CesarMaalouf/ggobi/data/flea.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata numRecords="74" color="2" glyph="fc 3" missingValue="NA">
<description source="ftp://...">
This data is from a paper by A. A. Lubischew, "On the Use of
Discriminant Functions in Taxonomy", Biometrics, Dec 1962, pp.455-477.

There are three species of flea-beetles: Ch. concinna, Ch. heptapotamica,
and Ch. heikertingeri, and 6 measurements on each.
    1 =  width of the first joint of the first tarsus in microns 
        (the sum of measurements for both tarsi).
    2 = the same for the second joint.
    3 = the maximal width of the head between the external edges of the
        eyes in 0.01 mm.
    4 = the maximal width of the aedeagus in the fore-part in microns.
    5 = the front angle of the aedeagus ( 1 unit = 7.5 degrees).
    6 = the aedeagus width from the side in microns.
</description>
<colormap  file="stdColorMap.xml" type="xml" size="4">
<color>1 0 0 </color>
<color>0 1 0 </color>
<color>0 0 1</color>
<color id="4" r=".5" g=".5" b="0" />
</colormap>
<variables count="6">
  <variable>tars1</variable>
  <variable>tars2</variable>
  <variable>head</variable>
  <variable>aede1</variable>
  <variable>aede2</variable>
  <variable>aede3</variable>
</variables>
<records>
<record label="Concinna" color="2">
191 131 53 150 15 104
</record>
<record id="temp" label="Concinna" color="2">
185 134 50 147 13 105
</record>
<record label="Concinna" color="2">
200 137 52 144 14 102
</record>
<record label="Concinna" color="2">
173 127 50 144 16 97
</record>
<record label="Concinna" color="2">
171 118 49 153 13 106
</record>
<record label="Concinna" color="2">
160 118 47 140 15 99
</record>
<record label="Concinna" color="2">
188 134 54 151 14 98
</record>
<record label="Concinna" color="2">
186 129 51 143 14 110
</record>
<record label="Concinna" color="2">
174 131 52 144 14 116
</record>
<record label="Concinna" color="2">
163 115 47 142 15 95
</record>
<record label="Concinna" color="2">
190 143 52 141 13 99
</record>
<record label="Concinna" color="2">
174 131 50 150 15 105
</record>
<record label="Concinna" color="2">
201 130 51 148 13 110
</record>
<record label="Concinna" color="2">
190 133 53 154 15 106
</record>
<record label="Concinna" color="2">
182 130 51 147 14 105
</record>
<record label="Concinna" color="2">
184 131 51 137 14 95
</record>
<record label="Concinna" color="2">
177 127 49 134 15 105
</record>
<record label="Concinna" color="2">
178 126 53 157 14 116
</record>
<record label="Concinna" color="2">
210 140 54 149 13 107
</record>
<record label="Concinna" color="2">
182 121 51 147 13 111
</record>
<record label="Concinna" color="2">
186 136 56 148 14 111
</record>
<record label="Heptapot.">
158 141 58 145 8 107
</record>
<record label="Heptapot." color="4">
146 119 51 140 11 111
</record>
<record label="Heptapot." color="4">
151 130 51 140 11 113
</record>
<record label="Heptapot." color="4">
122 113 45 131 10 102
</record>
<record label="Heptapot." color="4">
138 121 53 139 11 106
</record>
<record label="Heptapot." color="4">
132 115 49 139 10 98
</record>
<record label="Heptapot." color="4">
131 127 51 136 12 107
</record>
<record label="Heptapot." color="4">
135 123 50 129 11 107
</record>
<record label="Heptapot." color="4">
125 119 51 140 10 110
</record>
<record label="Heptapot." color="4">
130 120 48 137 9 106
</record>
<record label="Heptapot." color="4">
130 131 51 141 11 108
</record>
<record label="Heptapot." color="4">
138 127 52 138 9 101
</record>
<record label="Heptapot." color="4">
130 116 52 143 9 111
</record>
<record label="Heptapot." color="4">
143 123 54 142 11 95
</record>
<record label="Heptapot." color="4">
154 135 56 144 10 123
</record>
<record label="Heptapot." color="4">
147 132 54 138 10 102
</record>
<record label="Heptapot." color="4">
141 131 51 140 10 106
</record>
<record label="Heptapot." color="4">
131 116 47 130 9 102
</record>
<record label="Heptapot." color="4">
144 121 53 137 11 104
</record>
<record  label="Heptapot." color="4">
137 146 53 137 10 113
</record>
<record label="Heptapot." color="4">
143 119 53 136 9 105
</record>
<record label="Heptapot." color="4">
135 127 52 140 10 108
</record>
<record label="Heikert." color="7">
186 107 49 120 14 84
</record>
<record label="Heikert." color="7">
211 122 49 123 16 95
</record>
<record label="Heikert." color="7">
201 114 47 130 14 74
</record>
<record label="Heikert." color="7">
242 131 54 131 16 90
</record>
<record label="Heikert." color="7">
184 108 43 116 16 75
</record>
<record label="Heikert." color="7">
211 118 51 122 15 90
</record>
<record label="Heikert." color="7">
217 122 49 127 15 73
</record>
<record label="Heikert." color="7">
223 127 51 132 16 84
</record>
<record label="Heikert." color="7">
208 125 50 125 14 88
</record>
<record label="Heikert." color="7">
199 124 46 119 13 78
</record>
<record label="Heikert." color="7">
211 129 49 122 13 83
</record>
<record label="Heikert." color="7">
218 126 49 120 15 85
</record>
<record label="Heikert." color="7">
203 122 49 119 14 73
</record>
<record label="Heikert." color="7">
192 116 49 123 15 90
</record>
<record label="Heikert." color="7">
195 123 47 125 15 77
</record>
<record label="Heikert." color="7">
211 122 48 125 14 73
</record>
<record label="Heikert." color="7">
187 123 47 129 14 75
</record>
<record label="Heikert." color="7">
192 109 46 130 13 90
</record>
<record label="Heikert." color="7">
223 124 53 129 13 82
</record>
<record label="Heikert." color="7">
188 114 48 122 12 74
</record>
<record label="Heikert." color="7">
216 120 50 129 15 86
</record>
<record label="Heikert." color="7">
185 114 46 124 15 92
</record>
<record label="Heikert." color="7">
178 119 47 120 13 78
</record>
<record label="Heikert." color="7">
187 111 49 119 16 66
</record>
<record label="Heikert." color="7">
187 112 49 119 14 55
</record>
<record label="Heikert." color="7">
201 130 54 133 13 84
</record>
<record label="Heikert." color="7">
187 120 47 121 15 86
</record>
<record label="Heikert." color="7">
210 119 50 128 14 68
</record>
<record label="Heikert." color="7">
196 114 51 129 14 86
</record>
<record label="Heikert." color="7">
195 110 49 124 13 89
</record>
<record label="Heikert." color="7">
187 124 49 129 14 88
</record>
</records>
</ggobidata>
