=== CesarMaalouf/ggobi/data/ggobi.dtd
<!--
  The DTD for the GGobi input file format.
  See data/flea.xml in the distribution for an example.
 -->

<!ENTITY % glyphTypes " plus | x | oc | or | fc | fr | . ">
<!ENTITY % Boolean    " true | T | TRUE | false | F | FALSE ">

<!ELEMENT description ( #PCDATA )>
<!ATTLIST description
  source CDATA #IMPLIED
>  

<!ELEMENT variables ( variable|realvariable|categoricalvariable|integervariable|countervariable )*>

<!-- Allows the name to be the only entry -->
<!ELEMENT variable ( #PCDATA )>
<!ELEMENT realvariable ( (description)?,(quickHelp)? )>

<!ELEMENT categoricalvariable (description?, quickHelp?, levels, time?)?>
<!ELEMENT countervariable EMPTY>
<!ELEMENT integervariable (description?, quickHelp?, time?)>


<!ELEMENT level (#PCDATA)>
<!ATTLIST level
  value CDATA #IMPLIED
>

<!ELEMENT levels (level)+>
<!ATTLIST levels 
   count CDATA #REQUIRED
>

<!ELEMENT quickHelp (#PCDATA)>
<!ELEMENT time (#PCDATA)>


<!ELEMENT records ( record )*>
<!ELEMENT record  (#PCDATA|int|real|na|string)*>

<!ELEMENT ggobidata ((brush)?, (activeColorScheme)?, (data|edges)+)>


<!-- I don't see how a datad can have a colormap -->
<!ELEMENT data ((description)?, (colormap)?, variables, records, (edges)?)>

<!ELEMENT color ( #PCDATA) >
<!-- id is a number or either of "fg" and "bg" -->
<!ATTLIST color  
    id       CDATA  #IMPLIED
    r        CDATA  #IMPLIED
    g        CDATA  #IMPLIED
    b        CDATA  #IMPLIED
    range    CDATA  #IMPLIED
    name     CDATA  #IMPLIED
>

<!ELEMENT edge EMPTY>


<!ELEMENT edges (data*, edge+)>
<!ATTLIST edges 
     name  CDATA #IMPLIED
     count CDATA #REQUIRED
     data  CDATA #IMPLIED
>

<!ELEMENT activeColorScheme ( #PCDATA ) >
<!ATTLIST activeColorScheme
    name     CDATA   #IMPLIED
    file     CDATA   #IMPLIED
>
      
<!ELEMENT colormap (color)+ >
<!ATTLIST colormap
      size  CDATA  #REQUIRED
      range CDATA  #IMPLIED
      file  CDATA   #IMPLIED
      type  CDATA   "(xml | table)"
>
         

<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>



<!ATTLIST records
   count CDATA  #REQUIRED
   missingValue CDATA #IMPLIED
   color        CDATA #IMPLIED
   glyph        CDATA #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED   
>


<!ATTLIST variables
  count CDATA #REQUIRED
>

<!ENTITY % VariableAttributes "name          NMTOKEN #IMPLIED
    nickname      NMTOKEN #IMPLIED
    transformName NMTOKEN #IMPLIED
    missingValue  CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED">

<!ATTLIST variable
  %VariableAttributes;
>

<!ATTLIST integervariable
  %VariableAttributes;
>

<!ATTLIST countervariable
  %VariableAttributes;
>


<!ATTLIST realvariable
    name          CDATA   #IMPLIED
    nickname      NMTOKEN #IMPLIED
    quickHelp     CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    transformName CDATA   #IMPLIED
    missingValue  CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED
>

<!ATTLIST categoricalvariable
    name          NMTOKEN #IMPLIED
    nickname      NMTOKEN #IMPLIED
    quickHelp     CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    transformName NMTOKEN #IMPLIED
    missingValue  CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED
    levels        CDATA   "auto"
    count         CDATA   #IMPLIED
>

<!ATTLIST record
   label     CDATA                     #IMPLIED
   id        CDATA                     #IMPLIED
   color     CDATA                     #IMPLIED
   glyph     CDATA                     #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED
   hidden    ( %Boolean; )             "FALSE"

   source      CDATA  #IMPLIED
   destination CDATA  #IMPLIED
>   

<!ATTLIST edge
   source      CDATA  #REQUIRED
   destination CDATA  #REQUIRED
   color       CDATA  #IMPLIED
   width       CDATA  #IMPLIED
>


<!ATTLIST data
   name         CDATA #IMPLIED
   nickname     NMTOKEN #IMPLIED
   count        CDATA #IMPLIED
   missingValue CDATA #IMPLIED
   color        CDATA #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED   
>

<!-- to initialize the brushing color and glyph -->
<!ELEMENT brush ( #PCDATA )>
<!ATTLIST brush
   color        CDATA #IMPLIED
   glyph        CDATA #IMPLIED
>

<!ATTLIST ggobidata
    count  CDATA #IMPLIED
    ids    (alpha)  #IMPLIED
>

<!ELEMENT real ( #PCDATA )>
<!ELEMENT int ( #PCDATA )>
<!ELEMENT string ( #PCDATA )>
<!ELEMENT na EMPTY>

=== CesarMaalouf/ggobi/data/sat.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata>
<data name="SAT scores">
<description>
</description>
<variables count="10">
 <variable>STATE</variable>
 <variable>SAT</variable>
 <variable>EXPEND</variable>
 <variable>PERPUPIL</variable>
 <variable>ENROLL</variable>
 <variable>TEACHERS</variable>
 <variable>RATIO</variable>
 <variable>SALARY</variable>
 <variable>ATTEND</variable>
 <variable>COMPUTER</variable>
</variables>
<records count="51">
<record label="Alabama" color="0" glyph="fc 3">
1.000 1022.000 2188020.000 3197.000 724751.000 38845.000 18.700 25190.000 684453.000 28353.000
</record>
<record label="Alaska" color="0" glyph="fc 3">
2.000 923.000 739020.000 7716.000 106481.000 6272.000 17.000 41754.000 95776.000 8806.000
</record>
<record label="Arizona" color="0" glyph="fc 3">
3.000 853.000 2143148.000 3902.000 574890.000 31617.000 18.200 28499.000 549219.000 31676.000
</record>
<record label="Arkansas" color="0" glyph="fc 3">
4.000 986.000 1319370.000 3272.000 436387.000 27730.000 15.700 21395.000 403106.000 17734.000
</record>
<record label="California" color="0" glyph="fc 3">
5.000 906.000 19370242.000 4121.000 4618120.000 203342.000 22.700 34684.000 4699865.000 186468.000
</record>
<record label="Colorado" color="0" glyph="fc 3">
6.000 966.000 2266667.000 4408.000 560081.000 31398.000 17.800 29558.000 514232.000 32212.000
</record>
<record label="Connecticut" color="0" glyph="fc 3">
7.000 908.000 2984542.000 6857.000 460637.000 35502.000 13.000 37343.000 435227.000 21188.000
</record>
<record label="WashingonDC" color="0" glyph="fc 3">
8.000 903.000 479327.000 5422.000 96678.000 5898.000 16.400 31585.000 88397.000 3328.000
</record>
<record label="Delaware" color="0" glyph="fc 3">
9.000 846.000 584035.000 7850.000 84792.000 5936.000 14.300 36290.000 74398.000 3695.000
</record>
<record label="Florida" color="0" glyph="fc 3">
10.000 887.000 7245515.000 4563.000 1720930.000 100370.000 17.100 26974.000 1587882.000 86267.000
</record>
<record label="Georgia" color="0" glyph="fc 3">
11.000 847.000 4006069.000 3852.000 1107994.000 59916.000 18.500 26920.000 1039977.000 45715.000
</record>
<record label="Hawaii" color="0" glyph="fc 3">
12.000 888.000 643319.000 4121.000 167488.000 8737.000 19.200 30778.000 156114.000 4621.000
</record>
<record label="Idaho" color="0" glyph="fc 3">
13.000 965.000 571159.000 2838.000 214615.000 10425.000 20.600 22734.000 201219.000 8442.000
</record>
<record label="Illinois" color="0" glyph="fc 3">
14.000 982.000 7655153.000 4906.000 1794916.000 105097.000 17.100 31145.000 1560461.000 66679.000
</record>
<record label="Indiana" color="0" glyph="fc 3">
15.000 871.000 3779468.000 4284.000 960994.000 54029.000 17.800 29331.000 882175.000 45439.000
</record>
<record label="Iowa" color="0" glyph="fc 3">
16.000 1084.000 1925623.000 4285.000 478200.000 30327.000 15.800 25778.000 449418.000 25340.000
</record>
<record label="Kansas" color="0" glyph="fc 3">
17.000 1040.000 1712260.000 4443.000 426596.000 28122.000 15.200 27360.000 385364.000 21653.000
</record>
<record label="Kentucky" color="0" glyph="fc 3">
18.000 996.000 1918741.000 3347.000 637627.000 35788.000 17.800 24930.000 573221.000 27125.000
</record>
<record label="Louisiana" color="0" glyph="fc 3">
19.000 986.000 2468307.000 3317.000 786683.000 43203.000 18.200 22470.000 744142.000 27301.000
</record>
<record label="Maine" color="0" glyph="fc 3">
20.000 987.000 921931.000 4744.000 212902.000 14593.000 14.600 24938.000 194350.000 9126.000
</record>
<record label="Maryland" color="0" glyph="fc 3">
21.000 914.000 3505018.000 5758.000 688947.000 40899.000 16.800 33895.000 608699.000 33574.000
</record>
<record label="Massachusetts" color="0" glyph="fc 3">
22.000 905.000 4522119.000 5979.000 823428.000 60068.000 13.700 32221.000 756285.000 40731.000
</record>
<record label="Michigan" color="0" glyph="fc 3">
23.000 972.000 7493266.000 5116.000 1582785.000 79847.000 19.800 34823.000 1464766.000 69821.000
</record>
<record label="Minnesota" color="0" glyph="fc 3">
24.000 1066.000 3282296.000 4755.000 726950.000 42750.000 17.000 30660.000 690266.000 59184.000
</record>
<record label="Mississippi" color="0" glyph="fc 3">
25.000 988.000 1372290.000 2874.000 503326.000 27283.000 18.400 22578.000 477439.000 10890.000
</record>
<record label="Missouri" color="0" glyph="fc 3">
26.000 989.000 3096666.000 4263.000 806639.000 50693.000 15.900 26006.000 726451.000 35121.000
</record>
<record label="Montana" color="0" glyph="fc 3">
27.000 992.000 592454.000 4293.000 152191.000 9626.000 15.800 24421.000 138016.000 9004.000
</record>
<record label="Nebraska" color="0" glyph="fc 3">
28.000 1030.000 1105009.000 4360.000 269434.000 18003.000 15.000 23845.000 253426.000 12785.000
</record>
<record label="Nevada" color="0" glyph="fc 3">
29.000 926.000 615161.000 3791.000 176474.000 8699.000 20.300 28840.000 162256.000 8446.000
</record>
<record label="NewHampshire" color="0" glyph="fc 3">
30.000 932.000 733230.000 4807.000 169413.000 10442.000 16.200 26702.000 152536.000 4484.000
</record>
<record label="NewJersey" color="0" glyph="fc 3">
31.000 894.000 7309147.000 7549.000 1080871.000 79698.000 13.600 33037.000 968176.000 52330.000
</record>
<record label="NewMexico" color="0" glyph="fc 3">
32.000 1015.000 975552.000 3437.000 292425.000 15770.000 18.500 23897.000 280921.000 19192.000
</record>
<record label="NewYork" color="0" glyph="fc 3">
33.000 890.000 17127584.000 7663.000 2573715.000 172807.000 14.900 36654.000 2234976.000 139032.000
</record>
<record label="NorthCarolina" color="0" glyph="fc 3">
34.000 836.000 3892971.000 3874.000 1083156.000 61933.000 17.500 25738.000 1004837.000 64245.000
</record>
<record label="NorthDakota" color="0" glyph="fc 3">
35.000 1067.000 431814.000 3952.000 118809.000 7731.000 15.400 22249.000 109271.000 5537.000
</record>
<record label="Ohio" color="0" glyph="fc 3">
36.000 948.000 7425194.000 4649.000 1778544.000 101021.000 17.600 29671.000 1597117.000 72839.000
</record>
<record label="Oklahoma" color="0" glyph="fc 3">
37.000 1001.000 1822743.000 3379.000 580426.000 35116.000 16.500 22370.000 542693.000 25762.000
</record>
<record label="Oregon" color="0" glyph="fc 3">
38.000 927.000 2123241.000 5182.000 461752.000 25147.000 18.400 29390.000 409717.000 23961.000
</record>
<record label="Pennsylvania" color="0" glyph="fc 3">
39.000 886.000 8597355.000 5609.000 1659714.000 104379.000 15.900 31248.000 1532806.000 6994.000
</record>
<record label="RhodeIsland" color="0" glyph="fc 3">
40.000 895.000 736942.000 5976.000 133585.000 9216.000 14.500 34233.000 123321.000 4903.000
</record>
<record label="SouthCarolina" color="0" glyph="fc 3">
41.000 838.000 2118732.000 3736.000 615774.000 35877.000 17.200 25623.000 567133.000 30784.000
</record>
<record label="SouthDakota" color="0" glyph="fc 3">
42.000 1041.000 427522.000 3581.000 126910.000 8260.000 15.400 20530.000 119400.000 9378.000
</record>
<record label="Tennessee" color="0" glyph="fc 3">
43.000 1009.000 2668341.000 3491.000 821580.000 42657.000 19.300 25619.000 764354.000 29817.000
</record>
<record label="Texas" color="0" glyph="fc 3">
44.000 877.000 11761447.000 3877.000 3283707.000 196616.000 16.700 26527.000 3033684.000 152835.000
</record>
<record label="Utah" color="0" glyph="fc 3">
45.000 1036.000 1040104.000 2579.000 43119.000 17602.000 24.500 22852.000 403294.000 18776.000
</record>
<record label="Vermont" color="0" glyph="fc 3">
46.000 905.000 485226.000 5481.000 93381.000 6852.000 13.600 27092.000 88532.000 3147.000
</record>
<record label="Virginia" color="0" glyph="fc 3">
47.000 902.000 4151050.000 4539.000 982393.000 60883.000 16.100 28967.000 914445.000 52214.000
</record>
<record label="Washington" color="0" glyph="fc 3">
48.000 939.000 3204265.000 4352.000 790918.000 38780.000 20.400 29199.000 736345.000 41840.000
</record>
<record label="WestVirginia" color="0" glyph="fc 3">
49.000 939.000 1202486.000 3883.000 335912.000 22177.000 15.100 21904.000 309691.000 17170.000
</record>
<record label="Wisconsin" color="0" glyph="fc 3">
50.000 1013.000 3688311.000 5266.000 774857.000 48541.000 16.000 30779.000 700389.000 39970.000
</record>
<record label="Wyoming" color="0" glyph="fc 3">
51.000 978.000 491930.000 5375.000 97793.000 6693.000 14.600 27685.000 91515.000 7566.000
</record>
</records>
</data>
</ggobidata>

=== CesarMaalouf/ggobi/data/pigs.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata count="2">
<data name="pigs">
<description>
United Kingdom Pig Production, from the book 'Data' by Andrews and
Herzberg, and found on StatLib:
         http://lib.stat.cmu.edu/datasets/Andrews/T62.1

The time variables have been restructured.

GILTS: number of sows giving birth for the first time
PROFIT: ratio of price to an index of feed price
S/HERDSZ: ratio of the number of breeding pigs slaughtered to the total breeding herd size
PRODUCTION: number of pigs slaughtered that were reared for meat
HERDSZ: breeding herd size

</description>
<variables count="11">
<realvariable name="TIME" time="true" />
<realvariable name="YEAR" />
<realvariable name="QUARTER" />
<realvariable name="Q1" />
<realvariable name="Q2" />
<realvariable name="Q3" />
<realvariable name="GILTS" />
<realvariable name="PROFIT" />
<realvariable name="S/HERDSZ" />
<realvariable name="PRODUCTION" />
<realvariable name="HERDSZ" />
</variables>
<records count="48" glyph="fr 0" color="4">
<record id="1">
1.000 1967.000 1.000 1.000 0.000 0.000 105.000 8.075 10.800 2645.000 703.000
</record>
<record id="2">
2.000 1967.000 2.000 0.000 1.000 0.000 119.000 7.819 9.160 2540.000 722.000
</record>
<record id="3">
3.000 1967.000 3.000 0.000 0.000 1.000 119.000 7.366 9.380 2565.000 738.000
</record>
<record id="4">
4.000 1967.000 4.000 0.000 0.000 0.000 109.000 8.113 10.390 2776.000 747.000
</record>
<record id="5">
5.000 1968.000 1.000 1.000 0.000 0.000 117.000 7.380 9.440 2725.000 755.000
</record>
<record id="6">
6.000 1968.000 2.000 0.000 1.000 0.000 135.000 7.134 8.690 2623.000 780.000
</record>
<record id="7">
7.000 1968.000 3.000 0.000 0.000 1.000 126.000 7.222 9.600 2722.000 806.000
</record>
<record id="8">
8.000 1968.000 4.000 0.000 0.000 0.000 112.000 7.768 11.280 3004.000 807.000
</record>
<record id="9">
9.000 1969.000 1.000 1.000 0.000 0.000 116.000 7.386 11.200 2952.000 805.000
</record>
<record id="10">
10.000 1969.000 2.000 0.000 1.000 0.000 122.000 6.965 9.940 2968.000 801.000
</record>
<record id="11">
11.000 1969.000 3.000 0.000 0.000 1.000 115.000 6.478 11.210 2961.000 821.000
</record>
<record id="12">
12.000 1969.000 4.000 0.000 0.000 0.000 115.000 8.105 11.690 3243.000 809.000
</record>
<record id="13">
13.000 1970.000 1.000 1.000 0.000 0.000 122.000 8.060 9.670 3027.000 797.000
</record>
<record id="14">
14.000 1970.000 2.000 0.000 1.000 0.000 138.000 7.684 7.870 2902.000 831.000
</record>
<record id="15">
15.000 1970.000 3.000 0.000 0.000 1.000 135.000 7.580 8.150 3057.000 867.000
</record>
<record id="16">
16.000 1970.000 4.000 0.000 0.000 0.000 125.000 7.093 8.830 3331.000 862.000
</record>
<record id="17">
17.000 1971.000 1.000 1.000 0.000 0.000 115.000 6.129 10.510 3266.000 871.000
</record>
<record id="18">
18.000 1971.000 2.000 0.000 1.000 0.000 108.000 6.026 9.030 3290.000 864.000
</record>
<record id="19">
19.000 1971.000 3.000 0.000 0.000 1.000 100.000 6.679 9.930 3223.000 854.000
</record>
<record id="20">
20.000 1971.000 4.000 0.000 0.000 0.000 96.000 7.414 10.270 3501.000 846.000
</record>
<record id="21">
21.000 1972.000 1.000 1.000 0.000 0.000 107.000 7.112 9.560 3402.000 854.000
</record>
<record id="22">
22.000 1972.000 2.000 0.000 1.000 0.000 115.000 7.762 8.740 3278.000 851.000
</record>
<record id="23">
23.000 1972.000 3.000 0.000 0.000 1.000 123.000 7.645 10.320 3258.000 876.000
</record>
<record id="24">
24.000 1972.000 4.000 0.000 0.000 0.000 122.000 8.639 10.310 3400.000 876.000
</record>
<record id="25">
25.000 1973.000 1.000 1.000 0.000 0.000 128.000 7.667 9.970 3303.000 888.000
</record>
<record id="26">
26.000 1973.000 2.000 0.000 1.000 0.000 136.000 8.080 8.990 3228.000 903.000
</record>
<record id="27">
27.000 1973.000 3.000 0.000 0.000 1.000 140.000 6.678 12.220 3269.000 922.000
</record>
<record id="28">
28.000 1973.000 4.000 0.000 0.000 0.000 122.000 6.739 12.900 3396.000 902.000
</record>
<record id="29">
29.000 1974.000 1.000 1.000 0.000 0.000 102.000 5.569 14.000 3396.000 820.000
</record>
<record id="30">
30.000 1974.000 2.000 0.000 1.000 0.000 103.000 5.049 12.770 3386.000 819.000
</record>
<record id="31">
31.000 1974.000 3.000 0.000 0.000 1.000 89.000 5.642 12.610 3385.000 797.000
</record>
<record id="32">
32.000 1974.000 4.000 0.000 0.000 0.000 77.000 6.808 12.160 3262.000 751.000
</record>
<record id="33">
33.000 1975.000 1.000 1.000 0.000 0.000 89.000 6.636 11.160 3113.000 743.000
</record>
<record id="34">
34.000 1975.000 2.000 0.000 1.000 0.000 94.000 8.241 8.900 2851.000 744.000
</record>
<record id="35">
35.000 1975.000 3.000 0.000 0.000 1.000 104.000 7.968 10.240 2752.000 747.000
</record>
<record id="36">
36.000 1975.000 4.000 0.000 0.000 0.000 108.000 8.044 10.290 2919.000 764.000
</record>
<record id="37">
37.000 1976.000 1.000 1.000 0.000 0.000 119.000 7.791 10.030 2842.000 759.000
</record>
<record id="38">
38.000 1976.000 2.000 0.000 1.000 0.000 126.000 7.024 9.050 2834.000 807.000
</record>
<record id="39">
39.000 1976.000 3.000 0.000 0.000 1.000 119.000 6.102 12.000 2957.000 798.000
</record>
<record id="40">
40.000 1976.000 4.000 0.000 0.000 0.000 103.000 6.053 12.700 3305.000 811.000
</record>
<record id="41">
41.000 1977.000 1.000 1.000 0.000 0.000 96.000 5.941 12.950 3256.000 752.000
</record>
<record id="42">
42.000 1977.000 2.000 0.000 1.000 0.000 95.000 5.386 11.690 3151.000 761.000
</record>
<record id="43">
43.000 1977.000 3.000 0.000 0.000 1.000 80.000 5.811 12.650 3141.000 719.000
</record>
<record id="44">
44.000 1977.000 4.000 0.000 0.000 0.000 88.000 6.716 12.210 3266.000 741.000
</record>
<record id="45">
45.000 1978.000 1.000 1.000 0.000 0.000 93.000 6.923 10.680 3061.000 745.000
</record>
<record id="46">
46.000 1978.000 2.000 0.000 1.000 0.000 105.000 6.939 10.470 3018.000 764.000
</record>
<record id="47">
47.000 1978.000 3.000 0.000 0.000 1.000 107.000 6.705 11.050 3085.000 764.000
</record>
<record id="48">
48.000 1978.000 4.000 0.000 0.000 0.000 100.000 6.914 10.310 3242.000 786.000
</record>
</records>
</data>

<data name="edges">
<variables count="0" />
<records count="47">
<record source="1" destination="2" color="2"> </record>
<record source="2" destination="3" color="2"> </record>
<record source="3" destination="4" color="2"> </record>
<record source="4" destination="5" color="2"> </record>
<record source="5" destination="6" color="2"> </record>
<record source="6" destination="7" color="2"> </record>
<record source="7" destination="8" color="2"> </record>
<record source="8" destination="9" color="2"> </record>
<record source="9" destination="10" color="2"> </record>
<record source="10" destination="11" color="2"> </record>
<record source="11" destination="12" color="2"> </record>
<record source="12" destination="13" color="2"> </record>
<record source="13" destination="14" color="2"> </record>
<record source="14" destination="15" color="2"> </record>
<record source="15" destination="16" color="2"> </record>
<record source="16" destination="17" color="2"> </record>
<record source="17" destination="18" color="2"> </record>
<record source="18" destination="19" color="2"> </record>
<record source="19" destination="20" color="2"> </record>
<record source="20" destination="21" color="2"> </record>
<record source="21" destination="22" color="2"> </record>
<record source="22" destination="23" color="2"> </record>
<record source="23" destination="24" color="2"> </record>
<record source="24" destination="25" color="2"> </record>
<record source="25" destination="26" color="2"> </record>
<record source="26" destination="27" color="2"> </record>
<record source="27" destination="28" color="2"> </record>
<record source="28" destination="29" color="2"> </record>
<record source="29" destination="30" color="2"> </record>
<record source="30" destination="31" color="2"> </record>
<record source="31" destination="32" color="2"> </record>
<record source="32" destination="33" color="2"> </record>
<record source="33" destination="34" color="2"> </record>
<record source="34" destination="35" color="2"> </record>
<record source="35" destination="36" color="2"> </record>
<record source="36" destination="37" color="2"> </record>
<record source="37" destination="38" color="2"> </record>
<record source="38" destination="39" color="2"> </record>
<record source="39" destination="40" color="2"> </record>
<record source="40" destination="41" color="2"> </record>
<record source="41" destination="42" color="2"> </record>
<record source="42" destination="43" color="2"> </record>
<record source="43" destination="44" color="2"> </record>
<record source="44" destination="45" color="2"> </record>
<record source="45" destination="46" color="2"> </record>
<record source="46" destination="47" color="2"> </record>
<record source="47" destination="48" color="2"> </record>
</records>
</data>

</ggobidata>
