=== CesarMaalouf/ggobi/data/ggobi.dtd
<!--
  The DTD for the GGobi input file format.
  See data/flea.xml in the distribution for an example.
 -->

<!ENTITY % glyphTypes " plus | x | oc | or | fc | fr | . ">
<!ENTITY % Boolean    " true | T | TRUE | false | F | FALSE ">

<!ELEMENT description ( #PCDATA )>
<!ATTLIST description
  source CDATA #IMPLIED
>  

<!ELEMENT variables ( variable|realvariable|categoricalvariable|integervariable|countervariable )*>

<!-- Allows the name to be the only entry -->
<!ELEMENT variable ( #PCDATA )>
<!ELEMENT realvariable ( (description)?,(quickHelp)? )>

<!ELEMENT categoricalvariable (description?, quickHelp?, levels, time?)?>
<!ELEMENT countervariable EMPTY>
<!ELEMENT integervariable (description?, quickHelp?, time?)>


<!ELEMENT level (#PCDATA)>
<!ATTLIST level
  value CDATA #IMPLIED
>

<!ELEMENT levels (level)+>
<!ATTLIST levels 
   count CDATA #REQUIRED
>

<!ELEMENT quickHelp (#PCDATA)>
<!ELEMENT time (#PCDATA)>


<!ELEMENT records ( record )*>
<!ELEMENT record  (#PCDATA|int|real|na|string)*>

<!ELEMENT ggobidata ((brush)?, (activeColorScheme)?, (data|edges)+)>


<!-- I don't see how a datad can have a colormap -->
<!ELEMENT data ((description)?, (colormap)?, variables, records, (edges)?)>

<!ELEMENT color ( #PCDATA) >
<!-- id is a number or either of "fg" and "bg" -->
<!ATTLIST color  
    id       CDATA  #IMPLIED
    r        CDATA  #IMPLIED
    g        CDATA  #IMPLIED
    b        CDATA  #IMPLIED
    range    CDATA  #IMPLIED
    name     CDATA  #IMPLIED
>

<!ELEMENT edge EMPTY>


<!ELEMENT edges (data*, edge+)>
<!ATTLIST edges 
     name  CDATA #IMPLIED
     count CDATA #REQUIRED
     data  CDATA #IMPLIED
>

<!ELEMENT activeColorScheme ( #PCDATA ) >
<!ATTLIST activeColorScheme
    name     CDATA   #IMPLIED
    file     CDATA   #IMPLIED
>
      
<!ELEMENT colormap (color)+ >
<!ATTLIST colormap
      size  CDATA  #REQUIRED
      range CDATA  #IMPLIED
      file  CDATA   #IMPLIED
      type  CDATA   "(xml | table)"
>
         

<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>



<!ATTLIST records
   count CDATA  #REQUIRED
   missingValue CDATA #IMPLIED
   color        CDATA #IMPLIED
   glyph        CDATA #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED   
>


<!ATTLIST variables
  count CDATA #REQUIRED
>

<!ENTITY % VariableAttributes "name          NMTOKEN #IMPLIED
    nickname      NMTOKEN #IMPLIED
    transformName NMTOKEN #IMPLIED
    missingValue  CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED">

<!ATTLIST variable
  %VariableAttributes;
>

<!ATTLIST integervariable
  %VariableAttributes;
>

<!ATTLIST countervariable
  %VariableAttributes;
>


<!ATTLIST realvariable
    name          CDATA   #IMPLIED
    nickname      NMTOKEN #IMPLIED
    quickHelp     CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    transformName CDATA   #IMPLIED
    missingValue  CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED
>

<!ATTLIST categoricalvariable
    name          NMTOKEN #IMPLIED
    nickname      NMTOKEN #IMPLIED
    quickHelp     CDATA   #IMPLIED
    time          CDATA   #IMPLIED
    transformName NMTOKEN #IMPLIED
    missingValue  CDATA   #IMPLIED
    min           CDATA   #IMPLIED
    max           CDATA   #IMPLIED
    levels        CDATA   "auto"
    count         CDATA   #IMPLIED
>

<!ATTLIST record
   label     CDATA                     #IMPLIED
   id        CDATA                     #IMPLIED
   color     CDATA                     #IMPLIED
   glyph     CDATA                     #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED
   hidden    ( %Boolean; )             "FALSE"

   source      CDATA  #IMPLIED
   destination CDATA  #IMPLIED
>   

<!ATTLIST edge
   source      CDATA  #REQUIRED
   destination CDATA  #REQUIRED
   color       CDATA  #IMPLIED
   width       CDATA  #IMPLIED
>


<!ATTLIST data
   name         CDATA #IMPLIED
   nickname     NMTOKEN #IMPLIED
   count        CDATA #IMPLIED
   missingValue CDATA #IMPLIED
   color        CDATA #IMPLIED
   glyphSize ( 0 | 1 | 2 | 3 | 4 | 5 ) #IMPLIED
   glyphType ( %glyphTypes; )          #IMPLIED   
>

<!-- to initialize the brushing color and glyph -->
<!ELEMENT brush ( #PCDATA )>
<!ATTLIST brush
   color        CDATA #IMPLIED
   glyph        CDATA #IMPLIED
>

<!ATTLIST ggobidata
    count  CDATA #IMPLIED
    ids    (alpha)  #IMPLIED
>

<!ELEMENT real ( #PCDATA )>
<!ELEMENT int ( #PCDATA )>
<!ELEMENT string ( #PCDATA )>
<!ELEMENT na EMPTY>

=== CesarMaalouf/ggobi/data/sleep.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata count="1">
<data name="sleep">

<description>
Data from which conclusions  were  drawn  in  the  article  "Sleep  in
Mammals: Ecological and Constitutional Correlates" by Allison, T.  and
Cicchetti, D. (1976), _Science_, November 12, vol. 194,  pp.  732-734.
Includes brain and body  weight,  life  span,  gestation  time,  time
sleeping, and predation and danger indices for 62 mammals.

Variables below (from left to right) for Mammals Data Set:

species of animal 
body weight in kg 
brain weight in g 
slow wave ("nondreaming") sleep (hrs/day)
paradoxical ("dreaming") sleep (hrs/day)
total sleep (hrs/day)  (sum of slow wave and paradoxical sleep)
maximum life span (years)
gestation time (days)
predation index (1-5)
                1 = minimum (least likely to be preyed upon)
                5 = maximum (most likely to be preyed upon)
sleep exposure index (1-5)
                1 = least exposed (e.g. animal sleeps in a
                    well-protected den)
                5 = most exposed
overall danger index (1-5)
                (based on the above two indices and other information)
                1 = least danger (from other animals)
                5 = most danger (from other animals)

For more details, see

Allison, Truett and Cicchetti, Domenic V. (1976), "Sleep  in  Mammals:
Ecological and Constitutional  Correlates",  _Science_,  November  12,
vol. 194, pp. 732-734.

The above data set can be freely used for non-commercial purposes  and
can be freely distributed (permission in  writing  obtained  from  Dr.
Truett Allison).

Submitted by Roger Johnson
rjohnson@carleton.edu
</description>

<variables count="10">
<variable>BodyWgt</variable>
<variable>BrainWgt</variable>
<variable>NonD</variable>
<variable>Dream</variable>
<variable>Sleep</variable>
<variable>Span</variable>
<variable>Gest</variable>
<variable>Pred</variable>
<variable>Exp</variable>
<variable>Danger</variable>
</variables>
<records
 count="62" glyph="fr 0" color="0" missingValue="na">
<record label="African elephant">
6654.000 5712.000 na na 3.300 38.600 645.000 3.000 5.000 3.000
</record>
<record label="African giant pouched rat">
1.000 6.600 6.300 2.000 8.300 4.500 42.000 3.000 1.000 3.000
</record>
<record label="Arctic Fox">
3.385 44.500 na na 12.500 14.000 60.000 1.000 1.000 1.000
</record>
<record label="Arctic ground squirrel">
0.920 5.700 na na 16.500 na 25.000 5.000 2.000 3.000
</record>
<record label="Asian elephant">
2547.000 4603.000 2.100 1.800 3.900 69.000 624.000 3.000 5.000 4.000
</record>
<record label="Baboon">
10.550 179.500 9.100 0.700 9.800 27.000 180.000 4.000 4.000 4.000
</record>
<record label="Big brown bat">
0.023 0.300 15.800 3.900 19.700 19.000 35.000 1.000 1.000 1.000
</record>
<record label="Brazilian tapir">
160.000 169.000 5.200 1.000 6.200 30.400 392.000 4.000 5.000 4.000
</record>
<record label="Cat">
3.300 25.600 10.900 3.600 14.500 28.000 63.000 1.000 2.000 1.000
</record>
<record label="Chimpanzee">
52.160 440.000 8.300 1.400 9.700 50.000 230.000 1.000 1.000 1.000
</record>
<record label="Chinchilla">
0.425 6.400 11.000 1.500 12.500 7.000 112.000 5.000 4.000 4.000
</record>
<record label="Cow">
465.000 423.000 3.200 0.700 3.900 30.000 281.000 5.000 5.000 5.000
</record>
<record label="Desert hedgehog">
0.550 2.400 7.600 2.700 10.300 na na 2.000 1.000 2.000
</record>
<record label="Donkey">
187.100 419.000 na na 3.100 40.000 365.000 5.000 5.000 5.000
</record>
<record label="Eastern American mole">
0.075 1.200 6.300 2.100 8.400 3.500 42.000 1.000 1.000 1.000
</record>
<record label="Echidna">
3.000 25.000 8.600 0.000 8.600 50.000 28.000 2.000 2.000 2.000
</record>
<record label="European hedgehog">
0.785 3.500 6.600 4.100 10.700 6.000 42.000 2.000 2.000 2.000
</record>
<record label="Galago">
0.200 5.000 9.500 1.200 10.700 10.400 120.000 2.000 2.000 2.000
</record>
<record label="Genet">
1.410 17.500 4.800 1.300 6.100 34.000 na 1.000 2.000 1.000
</record>
<record label="Giant armadillo">
60.000 81.000 12.000 6.100 18.100 7.000 na 1.000 1.000 1.000
</record>
<record label="Giraffe">
529.000 680.000 na 0.300 na 28.000 400.000 5.000 5.000 5.000
</record>
<record label="Goat">
27.660 115.000 3.300 0.500 3.800 20.000 148.000 5.000 5.000 5.000
</record>
<record label="Golden hamster">
0.120 1.000 11.000 3.400 14.400 3.900 16.000 3.000 1.000 2.000
</record>
<record label="Gorilla">
207.000 406.000 na na 12.000 39.300 252.000 1.000 4.000 1.000
</record>
<record label="Gray seal">
85.000 325.000 4.700 1.500 6.200 41.000 310.000 1.000 3.000 1.000
</record>
<record label="Gray wolf">
36.330 119.500 na na 13.000 16.200 63.000 1.000 1.000 1.000
</record>
<record label="Ground squirrel">
0.101 4.000 10.400 3.400 13.800 9.000 28.000 5.000 1.000 3.000
</record>
<record label="Guinea pig">
1.040 5.500 7.400 0.800 8.200 7.600 68.000 5.000 3.000 4.000
</record>
<record label="Horse">
521.000 655.000 2.100 0.800 2.900 46.000 336.000 5.000 5.000 5.000
</record>
<record label="Jaguar">
100.000 157.000 na na 10.800 22.400 100.000 1.000 1.000 1.000
</record>
<record label="Kangaroo">
35.000 56.000 na na na 16.300 33.000 3.000 5.000 4.000
</record>
<record label="Lesser short-tailed shrew">
0.005 0.140 7.700 1.400 9.100 2.600 21.500 5.000 2.000 4.000
</record>
<record label="Little brown bat">
0.010 0.250 17.900 2.000 19.900 24.000 50.000 1.000 1.000 1.000
</record>
<record label="Man">
62.000 1320.000 6.100 1.900 8.000 100.000 267.000 1.000 1.000 1.000
</record>
<record label="Mole rat">
0.122 3.000 8.200 2.400 10.600 na 30.000 2.000 1.000 1.000
</record>
<record label="Mountain beaver">
1.350 8.100 8.400 2.800 11.200 na 45.000 3.000 1.000 3.000
</record>
<record label="Mouse">
0.023 0.400 11.900 1.300 13.200 3.200 19.000 4.000 1.000 3.000
</record>
<record label="Musk shrew">
0.048 0.330 10.800 2.000 12.800 2.000 30.000 4.000 1.000 3.000
</record>
<record label="N. American opossum">
1.700 6.300 13.800 5.600 19.400 5.000 12.000 2.000 1.000 1.000
</record>
<record label="Nine-banded armadillo">
3.500 10.800 14.300 3.100 17.400 6.500 120.000 2.000 1.000 1.000
</record>
<record label="Okapi">
250.000 490.000 na 1.000 na 23.600 440.000 5.000 5.000 5.000
</record>
<record label="Owl monkey">
0.480 15.500 15.200 1.800 17.000 12.000 140.000 2.000 2.000 2.000
</record>
<record label="Patas monkey">
10.000 115.000 10.000 0.900 10.900 20.200 170.000 4.000 4.000 4.000
</record>
<record label="Phalanger">
1.620 11.400 11.900 1.800 13.700 13.000 17.000 2.000 1.000 2.000
</record>
<record label="Pig">
192.000 180.000 6.500 1.900 8.400 27.000 115.000 4.000 4.000 4.000
</record>
<record label="Rabbit">
2.500 12.100 7.500 0.900 8.400 18.000 31.000 5.000 5.000 5.000
</record>
<record label="Raccoon">
4.288 39.200 na na 12.500 13.700 63.000 2.000 2.000 2.000
</record>
<record label="Rat">
0.280 1.900 10.600 2.600 13.200 4.700 21.000 3.000 1.000 3.000
</record>
<record label="Red fox">
4.235 50.400 7.400 2.400 9.800 9.800 52.000 1.000 1.000 1.000
</record>
<record label="Rhesus monkey">
6.800 179.000 8.400 1.200 9.600 29.000 164.000 2.000 3.000 2.000
</record>
<record label="Rock hyrax (Hetero">
0.750 12.300 5.700 0.900 6.600 7.000 225.000 2.000 2.000 2.000
</record>
<record label="Rock hyrax (Procavia hab)">
3.600 21.000 4.900 0.500 5.400 6.000 225.000 3.000 2.000 3.000
</record>
<record label="Roe deer">
14.830 98.200 na na 2.600 17.000 150.000 5.000 5.000 5.000
</record>
<record label="Sheep">
55.500 175.000 3.200 0.600 3.800 20.000 151.000 5.000 5.000 5.000
</record>
<record label="Slow loris">
1.400 12.500 na na 11.000 12.700 90.000 2.000 2.000 2.000
</record>
<record label="Star nosed mole">
0.060 1.000 8.100 2.200 10.300 3.500 na 3.000 1.000 2.000
</record>
<record label="Tenrec">
0.900 2.600 11.000 2.300 13.300 4.500 60.000 2.000 1.000 2.000
</record>
<record label="Tree hyrax">
2.000 12.300 4.900 0.500 5.400 7.500 200.000 3.000 1.000 3.000
</record>
<record label="Tree shrew">
0.104 2.500 13.200 2.600 15.800 2.300 46.000 3.000 2.000 2.000
</record>
<record label="Vervet">
4.190 58.000 9.700 0.600 10.300 24.000 210.000 4.000 3.000 4.000
</record>
<record label="Water opossum">
3.500 3.900 12.800 6.600 19.400 3.000 14.000 2.000 1.000 1.000
</record>
<record label="Yellow-bellied marmot">
4.050 17.000 na na na 13.000 38.000 3.000 1.000 1.000
</record>
</records>
</data>
</ggobidata>

=== CesarMaalouf/ggobi/data/test-cat-brushing.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata count="2">
<data name="a">
<description>
This is XML created by GGobi
</description>
<variables count="3">
   <realvariable name="x" nickname="x"/>
   <realvariable name="y" nickname="y"/>
  <categoricalvariable name="cat" nickname="ca">
    <levels count="10">
      <level value="1">a</level>
      <level value="2">b</level>
      <level value="3">c</level>
      <level value="4">d</level>
      <level value="5">e</level>
      <level value="6">f</level>
      <level value="7">g</level>
      <level value="8">h</level>
      <level value="9">i</level>
      <level value="10">j</level>
    </levels>
  </categoricalvariable>
</variables>
<records count="10" glyph="fc 1" color="0">
<record id="1" label="1">
1 1 1
</record>
<record id="2" label="2">
2 2 2
</record>
<record id="3" label="3">
3 3 3
</record>
<record id="4" label="4">
4 4 4
</record>
<record id="5" label="5">
5 5 5
</record>
<record id="6" label="6">
6 6 6
</record>
<record id="7" label="7">
7 7 7
</record>
<record id="8" label="8">
8 8 8
</record>
<record id="9" label="9">
9 9 9
</record>
<record id="10" label="10">
10 10 10
</record>
</records>
</data>
<data name="b">
<description>
This is XML created by GGobi
</description>
<variables count="3">
   <realvariable name="x" nickname="x"/>
   <realvariable name="y" nickname="y"/>
  <categoricalvariable name="cat" nickname="ca">
    <levels count="10">
      <level value="1">j</level>
      <level value="2">i</level>
      <level value="3">h</level>
      <level value="4">g</level>
      <level value="5">f</level>
      <level value="6">e</level>
      <level value="7">d</level>
      <level value="8">c</level>
      <level value="9">b</level>
      <level value="10">a</level>
    </levels>
  </categoricalvariable>
</variables>
<records count="10" glyph="fc 1" color="0">
<record id="1" label="1">
1 1 10
</record>
<record id="2" label="2">
2 2 9
</record>
<record id="3" label="3">
3 3 8
</record>
<record id="4" label="4">
4 4 7
</record>
<record id="5" label="5">
5 5 6
</record>
<record id="6" label="6">
6 6 5
</record>
<record id="7" label="7">
7 7 4
</record>
<record id="8" label="8">
8 8 3
</record>
<record id="9" label="9">
9 9 2
</record>
<record id="10" label="10">
10 10 1
</record>
</records>
</data>
</ggobidata>

=== CesarMaalouf/ggobi/data/perm4.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata count="2">
<data name="perm4">
<variables count="3">
  <realvariable name="Pos1" />
  <realvariable name="Pos2" />
  <realvariable name="Pos3" />
</variables>
<records count="24">
<record id="1" label="0123">	1.000000 0.500000 1 </record>
<record id="2" label="0132">	0.982963 0.629410 2 </record>
<record id="3" label="0213">	0.933013 0.750000 3 </record>
<record id="4" label="0231">	0.853553 0.853553 4 </record>
<record id="5" label="0312">	0.750000 0.933013 5 </record>
<record id="6" label="0321">	0.629410 0.982963 6 </record>
<record id="7" label="1023">	0.500000 1.000000 7 </record>
<record id="8" label="1032">	0.370590 0.982963 8 </record>
<record id="9" label="1203">	0.250000 0.933013 9 </record>
<record id="10" label="1230">	0.146447 0.853553 10 </record>
<record id="11" label="1302">	0.066987 0.750000 11 </record>
<record id="12" label="1320">	0.017037 0.629410 12 </record>
<record id="13" label="2013">	0.000000 0.500000 12 </record>
<record id="14" label="2031">	0.017037 0.370590 13 </record>
<record id="15" label="2103">	0.066987 0.250000 14 </record>
<record id="16" label="2130">	0.146447 0.146447 15 </record>
<record id="17" label="2301">	0.250000 0.066987 17 </record>
<record id="18" label="2310">	0.370590 0.017037 18 </record>
<record id="19" label="3012">	0.500000 0.000000 19 </record>
<record id="20" label="3021">	0.629409 0.017037 20 </record>
<record id="21" label="3102">	0.750000 0.066987 21 </record>
<record id="22" label="3120">	0.853553 0.146447 22 </record>
<record id="23" label="3201">	0.933013 0.250000 23 </record>
<record id="24" label="3210">	0.982963 0.370590 24 </record>
</records>
</data>

<data name="edges">
<records count="36">
<record source="1" destination="2" />
<record source="1" destination="3" />
<record source="3" destination="4" />
<record source="2" destination="5" />
<record source="5" destination="6" />
<record source="4" destination="6" />
<record source="1" destination="7" />
<record source="7" destination="8" />
<record source="2" destination="8" />
<record source="7" destination="9" />
<record source="9" destination="10" />
<record source="8" destination="11" />
<record source="11" destination="12" />
<record source="10" destination="12" />
<record source="3" destination="13" />
<record source="13" destination="14" />
<record source="4" destination="14" />
<record source="13" destination="15" />
<record source="9" destination="15" />
<record source="15" destination="16" />
<record source="10" destination="16" />
<record source="14" destination="17" />
<record source="17" destination="18" />
<record source="16" destination="18" />
<record source="5" destination="19" />
<record source="19" destination="20" />
<record source="6" destination="20" />
<record source="19" destination="21" />
<record source="11" destination="21" />
<record source="21" destination="22" />
<record source="12" destination="22" />
<record source="20" destination="23" />
<record source="17" destination="23" />
<record source="23" destination="24" />
<record source="22" destination="24" />
<record source="18" destination="24" />
</records>
</data>
</ggobidata>

=== CesarMaalouf/ggobi/data/stdColorMap.xml
<?xml version="1.0"?>
<!DOCTYPE colormap SYSTEM "ggobi.dtd">

<colormap size="10">
 <color>1.00 0.08 0.58 </color>
 <color>1.00 1.0 0.00  </color>
 <color>0.00 0.00 1.00 </color>
 <color>0.0  1.0  0.00 </color>
 <color>1.00 0.00 0.00 </color>
 <color>0.00 0.75 1.00 </color>
 <color>1.0  0.0 1.00  </color>
 <color>0.00 0.80 0.20 </color>
 <color>0.00 0.98 0.60 </color>
 <color>0.73 0.33 0.83 </color>
</colormap>

=== CesarMaalouf/ggobi/data/laser.xml
<?xml version="1.0"?>
<!DOCTYPE ggobidata SYSTEM "ggobi.dtd">

<ggobidata count="1">
<data name="laser">
<description>
This data came from an investigation of an experimental laser at
Bellcore.  It was a tunable laser, in the sense that both its
wavelength and power output were controllable.

Rotation helped the experimental physicists to characterize the
laser, which turned out not to be a very good one, due to its
unstable operating region.

The variables are:

  If     Ir     power   lambda

If and Ir are currents applied to the front and rear of the laser.
Power and lambda are the output power and wavelength. 

This data initially came to the statistics research group when
Janette Cooper asked Paul Tukey to help her analyze the data
she had collected to describe the laser.
</description>
<variables count="4">
 <realvariable name="ifront"/>
 <realvariable name="iback"/>
 <realvariable name="power"/>
 <realvariable name="lambda"/>
</variables>
<records
 count="64" glyph="fr 1" color="5">
<record label="1">
12.000 70.000 -38.300 1579.100
</record>
<record label="2">
13.000 70.000 -38.100 1579.100
</record>
<record label="3">
15.000 70.000 -36.500 1579.100
</record>
<record label="4">
19.000 70.000 -35.100 1579.000
</record>
<record label="5">
20.000 70.000 -35.100 1577.800
</record>
<record label="6">
20.000 70.000 -35.100 1578.100
</record>
<record label="7">
26.000 70.000 -34.200 1578.000
</record>
<record label="8">
30.000 70.000 -32.600 1578.000
</record>
<record label="9">
13.000 60.000 -40.900 1578.800
</record>
<record label="10">
14.000 60.000 -39.800 1578.900
</record>
<record label="11">
19.000 60.000 -37.000 1578.800
</record>
<record label="12">
21.000 60.000 -36.100 1577.800
</record>
<record label="13">
24.000 60.000 -35.400 1577.900
</record>
<record label="14">
40.000 60.000 -35.400 1577.900
</record>
<record label="15">
15.000 50.000 -45.700 1578.600
</record>
<record label="16">
20.000 50.000 -40.400 1578.600
</record>
<record label="17">
21.000 50.000 -37.400 1577.700
</record>
<record label="18">
25.000 50.000 -36.000 1577.800
</record>
<record label="19">
30.000 50.000 -34.100 1577.800
</record>
<record label="20">
40.000 50.000 -31.200 1577.800
</record>
<record label="21">
50.000 50.000 -29.500 1577.700
</record>
<record label="22">
22.000 40.000 -40.300 1577.500
</record>
<record label="23">
24.000 40.000 -39.500 1577.600
</record>
<record label="24">
31.000 40.000 -36.100 1577.600
</record>
<record label="25">
48.000 40.000 -30.900 1577.600
</record>
<record label="26">
55.000 40.000 -29.700 1577.600
</record>
<record label="27">
56.000 40.000 -29.500 1577.600
</record>
<record label="28">
57.000 40.000 -29.900 1575.700
</record>
<record label="29">
57.000 40.000 -29.900 1577.200
</record>
<record label="30">
60.000 40.000 -29.500 1575.700
</record>
<record label="31">
60.000 40.000 -29.500 1577.200
</record>
<record label="32">
27.000 30.000 -46.200 1577.400
</record>
<record label="33">
32.000 30.000 -41.000 1577.400
</record>
<record label="34">
37.000 30.000 -38.200 1577.300
</record>
<record label="35">
41.000 30.000 -36.200 1577.300
</record>
<record label="36">
46.000 30.000 -33.900 1577.300
</record>
<record label="37">
47.000 30.000 -34.100 1575.400
</record>
<record label="38">
49.000 30.000 -34.300 1575.500
</record>
<record label="39">
52.000 30.000 -35.100 1575.600
</record>
<record label="40">
54.000 30.000 -35.500 1575.600
</record>
<record label="41">
56.000 30.000 -36.000 1575.500
</record>
<record label="42">
59.000 30.000 -36.200 1575.500
</record>
<record label="43">
60.000 30.000 -35.600 1575.500
</record>
<record label="44">
60.000 30.000 -35.600 1577.100
</record>
<record label="45">
61.000 30.000 -34.500 1575.500
</record>
<record label="46">
61.000 30.000 -34.500 1577.100
</record>
<record label="47">
64.000 30.000 -33.500 1575.600
</record>
<record label="48">
64.000 30.000 -33.500 1577.200
</record>
<record label="49">
68.000 30.000 -31.700 1575.700
</record>
<record label="50">
68.000 30.000 -31.700 1577.400
</record>
<record label="51">
70.000 30.000 -31.100 1575.700
</record>
<record label="52">
70.000 30.000 -31.100 1577.400
</record>
<record label="53">
52.000 20.000 -44.500 1575.200
</record>
<record label="54">
53.000 20.000 -42.600 1575.200
</record>
<record label="55">
54.000 20.000 -38.500 1576.900
</record>
<record label="56">
55.000 20.000 -36.600 1577.000
</record>
<record label="57">
56.000 20.000 -35.200 1577.100
</record>
<record label="58">
58.000 20.000 -33.900 1577.200
</record>
<record label="59">
64.000 20.000 -31.800 1577.300
</record>
<record label="60">
67.000 20.000 -31.000 1577.400
</record>
<record label="61">
70.000 20.000 -30.000 1577.500
</record>
<record label="62">
74.000 20.000 -29.800 1577.600
</record>
<record label="63">
78.000 20.000 -29.400 1577.700
</record>
<record label="64">
85.000 20.000 -28.700 1577.800
</record>
</records>
</data>
</ggobidata>
